version: '3.8'
services:
  development-db:
    container_name: development-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - development-db:/var/lib/postgresql/data
volumes:
  development-db:
    driver: local