spring:
  application:
    name: ambulance-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ambulance_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        transaction:
          jta:
            platform: none
  logging:
    level:
      org.hibernate.SQL: DEBUG
server:
  port: 8085
